### ISSUE TITLE
German version is not updated with the latest GA release, 2.8.85.0

### ISSUE THREAD

**Issue by Justfyn** [MicrosoftDocs/Azure-RMSDocs.de-de#21]
[Hier Feedback eingeben]

German version mentions the latest GA version, 2.8.85.0 to be in Public Preview which should be corrected.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 4a4d7084-e736-2d1a-5376-58c1187a63ff
* Version Independent ID: f4942d95-dd63-6f30-6e69-a129d728068d
* Content: [Azure Information Protection vereinheitlichte Bezeichnung für den Client Versionsverlauf & Unterstützungs Richtlinie](https://docs.microsoft.com/de-de/azure/information-protection/rms-client/unifiedlabelingclient-version-release-history#feedback)
* Content Source: [Azure-RMSDocs/rms-client/unifiedlabelingclient-version-release-history.md](https://github.com/MicrosoftDocs/Azure-RMSDocs.de-de/blob/live/Azure-RMSDocs/rms-client/unifiedlabelingclient-version-release-history.md)
* Service: **information-protection**
* Sub-service: **v2client**
* GitHub Login: @batamig
* Microsoft Alias: **bagol**

**Comment by JasonCard** [comment]
@Justfyn Thank you for reporting this issue. German version is now up-to-date.
